# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ffc76bf618db64c2cbc3bcae852d07fa2e6d660da554a9d4e77b7a545d8e206b7d0546b9f23654612b4bdfed30691ab3cbafd158e1df122ecf77c10450276dd

test:
  secret_key_base: 11a1886acb6bd73da104b51f859e36ce714302722953226d2607613e213843c25663082f849d5398ce55977a1f20e78d5106666ce2871dd3e4fffde66254bdfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
